#!/usr/bin/env python

"""Build index from all current posts."""

import os
import os.path as osp


SRC_DPATH = osp.join(osp.dirname(__file__), osp.pardir, osp.pardir, 'src')

def build_index():
  """Created minimal index Markdown file with links to all posts."""
  fnames = os.listdir(osp.join(SRC_DPATH, 'posts'))
  with open(osp.join(SRC_DPATH, 'index.md'), 'w') as writer:
    for fname in fnames:
      post = osp.splitext(fname)[0]
      title = _get_title(osp.join(SRC_DPATH, 'posts', fname))
      writer.write('+ [%s](/pub/posts/%s.html)\n' % (title, post))

def _get_title(fpath):
  """Extract title from Markdown file."""
  with open(fpath) as reader:
    for line in reader:
      if line.startswith('# '):
        return line[2:]
  raise Exception('no title found')


if __name__ == '__main__':
  build_index()
